version: '3'

services: 
  php:
    build:
      context: ./backend
    container_name: php-apache
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
    
  nodejs:
    build:
      context: ./frontend
    user: $UID:$GID
    stdin_open: true
    tty: true
    container_name: nodejs
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/app
    working_dir: /usr/app
